---
#                                  _                 __      _       __     ___            _        
#  ___ _   _ _ __   ___ _ ____   _(_)___  ___  _ __ / /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
# / __| | | | '_ \ / _ \ '__\ \ / / / __|/ _ \| '__| || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# \__ \ |_| | |_) |  __/ |   \ V /| \__ \ (_) | |  | || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
# |___/\__,_| .__/ \___|_|    \_/ |_|___/\___/|_|  | || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
#           |_|                                     \_\_|        |___/_/                            
# install-pkg
- name: install-pkg | Python 2.7 should have been installed(0)
  register: python27
  ignore_errors: true
  failed_when: python27.rc > 0
  changed_when: python27.rc > 0
  raw: which python 2> /dev/null

- block:
  - name: install-pkg | RedHat | Python 2.7 should have been installed(1)
    when: python27 is failed
    raw:  /usr/bin/yum -y install python

  - name: install-pkg | RedHat | pip for Python 2.7 should be installed(2)
    when: python27 is failed
    raw:  /usr/bin/yum -y install python2-pip
  when: ansible_os_family == "RedHat"

- name: install-pkg | RedHat | supervisor should be installed
  pip:
    name:  "supervisor"
    state: "present"

